### ISSUE TITLE
Make it impossible to enter non-numbers in "amount" fields

### ISSUE THREAD

**Issue by TedTed** [danielkeller/budge_it#28]
This would be a little nicer than having an error message at the end.

**Comment by danielkeller** [comment]
I'm not going to do this, because
* It's possible to enter non-numbers using only the characters that are valid in a number, and you might do this in the process of entering a valid number, so you have to check at the end anyway.
* This is usually implemented by editing the contents the a field while the user types or intercepting kepress events. This is very hard to do without breaking the usual interactions in lots of subtle ways, eg moving the cursor to the end of the field unexpectedly, or not work on mobile, or whatever.

Instead I'll add an html validation thingy that will highlight the field and keep you from submitting.
