### ISSUE TITLE
I can't make a transaction recurring

### ISSUE THREAD

**Issue by TedTed** [danielkeller/budge_it#49]
I tried to add a new recurring transaction. I added it as normal in the quick add UI, but on the right side of the screen, I couldn't seem to make it recurring. (The "Don't repeat" UI element is greyed out and I can't click on it.) Not sure what I should do here

**Comment by danielkeller** [comment]
Making existing transactions recurring isn’t allowed because someone you shared the transaction with might have already categorized it, and making it recur would let you put new stuff in their categories on their behalf. If it’s already recurring when they categorize it this is ok because they know it will recur.
